// <auto-generated />
using System;
using Apteka.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Apteka.Migrations
{
    [DbContext(typeof(DataContext1))]
    partial class DataContext1ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11");

            modelBuilder.Entity("Apteka.Models.AEmployee", b =>
                {
                    b.Property<int>("EmployeeId1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId1");

                    b.HasIndex("EmployeeId1")
                        .IsUnique();

                    b.ToTable("Employees1");
                });

            modelBuilder.Entity("Apteka.Models.AItem", b =>
                {
                    b.Property<int>("Id1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cuantity1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price1")
                        .HasColumnType("REAL");

                    b.HasKey("Id1");

                    b.HasIndex("Id1")
                        .IsUnique();

                    b.ToTable("Items1");
                });

            modelBuilder.Entity("Apteka.Models.ASelling", b =>
                {
                    b.Property<int>("SellingId1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AEmployee1EmployeeId1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime1")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId1")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price1")
                        .HasColumnType("REAL");

                    b.HasKey("SellingId1");

                    b.HasIndex("AEmployee1EmployeeId1");

                    b.HasIndex("SellingId1")
                        .IsUnique();

                    b.ToTable("Sellings1");
                });

            modelBuilder.Entity("Apteka.Models.ASellingContents", b =>
                {
                    b.Property<int>("SellingContentsId1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AItem1Id1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ASelling1SellingId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemAmmaunt1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId1")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price1")
                        .HasColumnType("REAL");

                    b.Property<string>("SCName1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SellingId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("SellingContentsId1");

                    b.HasIndex("AItem1Id1");

                    b.HasIndex("ASelling1SellingId1");

                    b.HasIndex("SellingContentsId1")
                        .IsUnique();

                    b.ToTable("SellingContents1");
                });

            modelBuilder.Entity("Apteka.Models.ASelling", b =>
                {
                    b.HasOne("Apteka.Models.AEmployee", "AEmployee1")
                        .WithMany("ASellings1")
                        .HasForeignKey("AEmployee1EmployeeId1");
                });

            modelBuilder.Entity("Apteka.Models.ASellingContents", b =>
                {
                    b.HasOne("Apteka.Models.AItem", "AItem1")
                        .WithMany("ASellingContents1")
                        .HasForeignKey("AItem1Id1");

                    b.HasOne("Apteka.Models.ASelling", "ASelling1")
                        .WithMany("ASellingContents1")
                        .HasForeignKey("ASelling1SellingId1");
                });
#pragma warning restore 612, 618
        }
    }
}
